### PR TITLE
Updating datastore escape apps

### PR DESCRIPTION
**Pull request by fhightower**

### CODE REVIEW

**Comment by wesinator** [comment]
https://github.com/fhightower/threatconnect-playbooks/blob/410f969042db9e1ce5aba3b367ecf86e3e4b4d20/playbooks/TCPB-HT-Unstructured%20Indicator%20Importer%20Attribute%20Recorder/%5Bunstructured%20importer%5D%20Store%20Attributes%20in%20Datastore%20-%20post%205.6.pbx#L49

Can you update the owner to use the current owner/org ?

**Comment by wesinator** [comment]
@fhightower this still isn't working after importing new version for the data escape, and importing new PB for the unstructured importer.

```
TRACE | 17:38:54 | Datastore path: $org.3_app-data/app-data/attributeTest
-- | -- | --
TRACE | 17:38:54 | Error  Response:  {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed  to parse"}],"type":"mapper_parsing_exception","reason":"failed to  parse","caused_by":{"type":"json_parse_exception","reason":"Unexpected  character ('t' (code 116)): was expecting comma to separate Object  entries  at [Source:  org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@55b9f883;  line: 1, column: 21]"}},"status":400}
TRACE | 17:38:54 | ES Response Code: 400
INFO | 17:38:54 | DataStore finished with status: 1
```

**Comment by fhightower** [comment]
> https://github.com/fhightower/threatconnect-playbooks/blob/410f969042db9e1ce5aba3b367ecf86e3e4b4d20/playbooks/TCPB-HT-Unstructured%20Indicator%20Importer%20Attribute%20Recorder/%5Bunstructured%20importer%5D%20Store%20Attributes%20in%20Datastore%20-%20post%205.6.pbx#L49
> 
> Can you update the owner to use the current owner/org ?

Good catch, I'll update the owner

> @fhightower this still isn't working after importing new version for the data escape, and importing new PB for the unstructured importer.
> 
> ```
> TRACE | 17:38:54 | Datastore path: $org.3_app-data/app-data/attributeTest
> -- | -- | --
> TRACE | 17:38:54 | Error  Response:  {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed  to parse"}],"type":"mapper_parsing_exception","reason":"failed to  parse","caused_by":{"type":"json_parse_exception","reason":"Unexpected  character ('t' (code 116)): was expecting comma to separate Object  entries  at [Source:  org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@55b9f883;  line: 1, column: 21]"}},"status":400}
> TRACE | 17:38:54 | ES Response Code: 400
> INFO | 17:38:54 | DataStore finished with status: 1
> ```

@wesinator : Thanks for reporting this; before you installed this updated playbook, did you delete the existing `[unstructured importer] Store Attributes in Datastore` playbook and `[utility] Escape String for Datastore` component? I forgot to mention this, but those may need to be deleted before this new version will work.

**Comment by wesinator** [comment]
> @wesinator : Thanks for reporting this; before you installed this updated playbook, did you delete the existing `[unstructured importer] Store Attributes in Datastore` playbook and `[utility] Escape String for Datastore` component? I forgot to mention this, but those may need to be deleted before this new version will work.

I deleted the old playbooks, imported new ones and it worked. Seems update playbook did not correctly update to the new changes.

**Comment by fhightower** [comment]
Ok, glad to hear the new one is working; I'll look into the problem when updating the component. Thanks again for making a note of this!

**Comment by fhightower** [comment]
@wesinator : Following back up on your point that the `[utility] Escape String for Datastore` component was not updated: it is expected behaviour that a component is not updated if a component with the same name already exists.

**Comment by wesinator** [comment]
> @wesinator : Following back up on your point that the `[utility] Escape String for Datastore` component was not updated: it is expected behaviour that a component is not updated if a component with the same name already exists.

ok - this should probably be documented

**Pull request merged**
