### PR TITLE
Fixing datastore path in which the attributes will be stored

### PR DESCRIPTION
**Pull request by fhightower**

### CODE REVIEW

**Comment by wesinator** [comment]
When I import new version 5.6, I get the following growl error :
` An Error has Occurred
Unable to install this playbook. The following apps are missing: DataStore`

image

**Comment by fhightower** [comment]
Ah, yes. This playbook uses the most recent version of the datastore playbook app. Can you check in the TC Exchange Settings (/auth/apps/settings/app-settings.xhtml#/) to see if there is an update available for the datastore app or a new datastore app?

**Comment by wesinator** [comment]
DataStore 2.0.0
image

no updates 
I actually applied all updates recently

**Comment by fhightower** [comment]
Interesting. This playbook require a datastore app version 3.0.0. I'll see if I can create a version with the datastore v2.0.0.

**Comment by wesinator** [comment]
> Interesting. This playbook require a datastore app version 3.0.0. I'll see if I can create a version with the datastore v2.0.0.

Ok, that error should say "the DataStore app requires version x.x.x" , or something like that.

Was datastore app 3.0.0 just released recently ?

**Comment by fhightower** [comment]
No idea when it was released. Does the Datastore 3.0.0 app show up under the "Updates" tab in the TC Exchange Settings page in ThreatConnect (/auth/apps/settings/app-settings.xhtml#/)?

**Comment by wesinator** [comment]
> No idea when it was released. Does the Datastore 3.0.0 app show up under the "Updates" tab in the TC Exchange Settings page in ThreatConnect (/auth/apps/settings/app-settings.xhtml#/)?

no it doesn't

**Pull request merged**
